resources: /resources
events: /events
contact: /contact
home: {{site.baseurl}}
gamejam:
    url: /gamejam
    march2017: /gamejam/march2017
    october2017: /gamejam/october2017
    march2018: /gamejam/march2018
